### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by jlgarridol** [JoseluCross/GESPRO_PracticaControlVersiones_1718#7]
It is been a while since the last time the project was updated. It would be nice to update all the dependencies before we start working on new features again.

**Comment by Josemi** [comment]
Me equivoque al asignarme y pasar a in progress esta tarea, tenía que hacer otra que se llama muy parecido. Está ya todo cambiado.

**Comment by jlgarridol** [comment]
Sin problemas
